name: "Pipeline CI/CD - Observabilidad, Seguridad y Despliegue"

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  # --------- SNYK ---------
  analisis-vulnerabilidad:
    name: "Snyk Security Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk Test (Seguridad)
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --severity-threshold=high --file=suscripciones/pom.xml

  # --------- DOCKERHUB ---------
  levantar-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/suscripciones:latest .

      - name: Push Docker image

        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/suscripciones:latest