name: "Pipeline CI/CD - Observabilidad, Seguridad y Despliegue"

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  # --------- SNYK ---------
  analisis-vulnerabilidad:
    name: "Snyk Security Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk Test (Seguridad)
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --severity-threshold=high --file=suscripciones/pom.xml

  # --------- DOCKERHUB ---------
  build-and-push:
    name: "Build Docker Image & Push"
    runs-on: ubuntu-latest
    
    steps:  
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
          
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          
      - name: "Extract Metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/suscripciones-api
          tags: |
            type=raw,value=latest
            type=sha,value={{sha}}

      - name: "Build and Push Image"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "Finalización Exitosa"
        run: echo "🚀 Imagen subida a Docker Hub de forma segura tras pasar todas las pruebas."   